# Generated by Django 5.2.16 on 2026-07-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='crm, telegram, shop, ai, bots, vpn…', max_length=64, unique=True, verbose_name='Ключ раздела')),
                ('label', models.CharField(max_length=120, verbose_name='Название в интерфейсе')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Раздел витрины',
                'verbose_name_plural': 'Разделы витрины',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('points', models.JSONField(blank=True, default=list, help_text='Список строк, например ["CRM", "BYN"]', verbose_name='Теги / пункты')),
                ('image', models.ImageField(blank=True, upload_to='showcase/%Y/%m/', verbose_name='Картинка')),
                ('image_url', models.CharField(blank=True, default='', help_text='Например assets/showcase/crm-1.png — если картинка уже на фронте', max_length=500, verbose_name='Или путь к уже лежащему файлу')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.showcasecategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Карточка проекта',
                'verbose_name_plural': 'Карточки проектов',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
