# Generated by Django 5.2.16 on 2026-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasecategory',
            name='slug',
            field=models.SlugField(help_text='crm, telegram, shop, ai, bots, vpn, landings…', max_length=64, unique=True, verbose_name='Ключ раздела'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Например assets/showcase/crm-1.webp — файл из папки фронта', max_length=500, verbose_name='Или путь к уже лежащему файлу'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='points',
            field=models.JSONField(blank=True, default=list, help_text='Список строк — плашки под описанием', verbose_name='Теги / пункты'),
        ),
    ]
