# Generated by Django 5.2.16 on 2026-07-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Сессия')),
                ('page_path', models.CharField(db_index=True, max_length=255, verbose_name='Страница / якорь')),
                ('page_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('referrer', models.CharField(blank=True, default='', max_length=500, verbose_name='Referrer')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Страна')),
                ('country_code', models.CharField(blank=True, default='', max_length=8, verbose_name='Код страны')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='Город')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('device', models.CharField(blank=True, default='', max_length=32, verbose_name='Устройство')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний ping')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Секунд на странице')),
                ('is_bounce', models.BooleanField(default=True, verbose_name='Отказ')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['page_path', '-started_at'], name='analytics_p_page_pa_c3166b_idx'), models.Index(fields=['country', '-started_at'], name='analytics_p_country_5e6a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('view', 'Просмотр'), ('heartbeat', 'Heartbeat'), ('leave', 'Уход'), ('click', 'Клик'), ('section', 'Секция')], db_index=True, max_length=32)),
                ('page_path', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.pagevisit')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
    ]
