# Generated by Django 5.2.16 on 2026-07-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сырое событие', 'verbose_name_plural': 'Сырые события (журнал)'},
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда'),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Открыл страницу'), ('heartbeat', 'На сайте (пинг)'), ('leave', 'Ушёл со страницы'), ('click', 'Клик'), ('section', 'Перешёл к секции'), ('showcase', 'Смотрел витрину')], db_index=True, max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='page_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.pagevisit', verbose_name='Визит'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='is_bounce',
            field=models.BooleanField(default=True, verbose_name='Отказ (<15 сек)'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Откуда пришёл'),
        ),
        migrations.CreateModel(
            name='ProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Сессия')),
                ('category_slug', models.SlugField(max_length=64, verbose_name='Раздел (ключ)')),
                ('category_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Раздел')),
                ('item_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Проект')),
                ('item_index', models.PositiveIntegerField(default=0, verbose_name='№ в карусели')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_interests', to='analytics.pagevisit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Интерес к продукту',
                'verbose_name_plural': 'Интерес к продуктам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category_slug', '-created_at'], name='analytics_p_categor_3e9118_idx'), models.Index(fields=['-created_at'], name='analytics_p_created_af8285_idx')],
            },
        ),
    ]
