# Generated by Django 5.2.16 on 2026-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact', models.CharField(help_text='Telegram / телефон / email', max_length=255, verbose_name='Контакт')),
                ('message', models.TextField(blank=True, default='', verbose_name='Задача')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(default='site_form', max_length=64, verbose_name='Источник')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Страница')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('country', models.CharField(blank=True, default='', max_length=64, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='Город')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
