# Generated by Django 5.2.16 on 2026-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LiveDev', max_length=120, verbose_name='Название сайта')),
                ('contact_email', models.EmailField(default='live-dev@mail.ru', max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(default='+375 29 894-54-62', max_length=64, verbose_name='Телефон')),
                ('contact_telegram', models.CharField(default='@solovey_ev', max_length=64, verbose_name='Telegram')),
                ('yandex_metrika_id', models.CharField(blank=True, default='', help_text='Бесплатный счётчик с metrika.yandex.ru', max_length=32, verbose_name='Яндекс.Метрика ID')),
                ('yandex_metrika_webvisor', models.BooleanField(default=True, verbose_name='Метрика: вебвизор')),
                ('yandex_direct_counter', models.CharField(blank=True, default='', help_text='Опционально: идентификатор для рекламы. Пока можно оставить пустым.', max_length=128, verbose_name='Яндекс.Директ / РСЯ (метка)')),
                ('yandex_ads_enabled', models.BooleanField(default=False, verbose_name='Включить Яндекс.Рекламу (скрипты)')),
                ('yandex_ads_block_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID рекламного блока РСЯ')),
                ('google_analytics_id', models.CharField(blank=True, default='', help_text='Бесплатный GA4 Measurement ID', max_length=32, verbose_name='Google Analytics 4 (G-XXXX)')),
                ('google_ads_id', models.CharField(blank=True, default='', help_text='Позже для рекламы; пока можно пусто', max_length=32, verbose_name='Google Ads (AW-XXXX)')),
                ('google_tag_manager_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Google Tag Manager (GTM-XXXX)')),
                ('analytics_enabled', models.BooleanField(default=True, verbose_name='Своя аналитика (визиты/страны/IP)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
