# Generated by Django 5.2.16 on 2026-07-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Контакты и счётчики', 'verbose_name_plural': 'Контакты и счётчики'},
        ),
    ]
