# Generated by Django 5.2.16 on 2026-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegram_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='От @BotFather. Можно также задать в .env как TELEGRAM_BOT_TOKEN.', max_length=128, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Куда слать заявки: ваш user id или id группы. Напишите боту /start, затем откройте https://api.telegram.org/bot<TOKEN>/getUpdates', max_length=64, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='analytics_enabled',
            field=models.BooleanField(default=True, verbose_name='Своя аналитика LiveDev (визиты / интерес)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_ads_id',
            field=models.CharField(blank=True, default='', help_text='Когда запускаете Google Ads.', max_length=32, verbose_name='Google Ads (AW-XXXX)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Measurement ID из analytics.google.com', max_length=32, verbose_name='Google Analytics 4 (G-XXXX)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_ads_block_id',
            field=models.CharField(blank=True, default='', help_text='Только если показываете баннеры РСЯ на своём сайте.', max_length=64, verbose_name='ID рекламного блока РСЯ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_ads_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить скрипты Яндекс.Рекламы (РСЯ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_direct_counter',
            field=models.CharField(blank=True, default='', help_text='Пока рекламу не запускаете — можно пусто.', max_length=128, verbose_name='Яндекс.Директ / цель (метка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Числовой ID счётчика с metrika.yandex.ru', max_length=32, verbose_name='Яндекс.Метрика ID'),
        ),
    ]
