# Generated by Django 5.2.16 on 2026-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegram_bot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Создай бота у @BotFather → вставь токен сюда. Потом напиши боту /start и нажми «Подключить бота».', max_length=128, verbose_name='Токен бота (@BotFather)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Не надо искать вручную: напиши боту /start → кнопка «Подключить бота». Это просто адрес твоего Telegram, иначе бот не знает, кому писать.', max_length=64, verbose_name='Куда слать (подставится само)'),
        ),
    ]
